### PR TITLE
Restructuring of projects

### PR DESCRIPTION
**Pull request by thoemmi**
This PR will uplift **resourcelib** to 2017:

- [x] Use new [.csproj format](https://docs.microsoft.com/de-de/dotnet/core/tools/csproj)
- [x] Support .NET Standard 2.0
- [x] Minimum supported of .NET Framework is 4.5.2 (older .NET versions [aren't supported anymore](https://github.com/Microsoft/dotnet/blob/master/releases/README.md) anyway)
- [x] [Semantic versioning](http://semver.org/) using [GitVersion](https://gitversion.readthedocs.io/en/latest/)
- [x]  Re-establish Continuous Integration with AppVeyor (need approval by @dblock so I can associate an AppVeyor project with this repo)
- [x] Fix NuGet package metadata
- [x] Copy the documentation to Github wiki and delete from repository
- [x] Don't release ZIP files anymore. NuGet is the modern way to publish .NET libraries.
- [x] Automatically publish build from master branch to NuGet gallery (continuous deployment).

Unfortunately, `System.Drawing.Common` (the netstandard replacement of the old `System.Drawing`) is available only as prerelease for .NET Core 2.0 apps only at the moment, but they're working on it. See dotnet/corefx#20325 and dotnet/corefx#24675 for details. The latter should be closed, so we don't need to reference a prerelease version of  `System.Drawing.Common`.

This PR supersedes #57 and #58.

/cc @dblock @jairbubbles @wjk

### CODE REVIEW

**Comment by jairbubbles** [comment]
Hi, you're targetting `netcoreapp2.0` I'm pretty sure it's not equivalent to `netstandard2.0` as you have access to a larger API with .NET Core.

Also, @wjk was targetting a lower version of .NET Standard which offered more compatibility (but with no support with System.Drawing).

**Comment by thoemmi** [comment]
@jairbubbles please see the paragraph I wrote about `System.Drawing.Common`. At the moment that package supports `netcoreapp2.0` only. As soon as dotnet/corefx#24675 is fixed, I can change the target to `netstandard2.0`.

I've opted against netstandard < 2.0, because I don't think it's relevant for apps managing Win32 resources. They're either .NET Framework, or .NET Standard 2.0, which is compatible with .NET Framework (4.7.1)

**Comment by jairbubbles** [comment]
Sure no problem, it just didn't match your Pull Request description. Do you want to wait for the package to be officially released?

Regarding the version (.NET Framework and .NET Standard) the lower the better! The client is responsible of the version he's using, if he wants to use an old version that he's not supported anymore that's his problem.
As the library do not use any new API provided by recent versions of .NET I would stick to the old version.

**Comment by thoemmi** [comment]
> Sure no problem, it just didn't match your Pull Request description. Do you want to wait for the package to be officially released?

The PR is still in progress, that's why there's `[WIP]` in the title. For clarity I've just added a label too.

> As the library do not use any new API provided by recent versions of .NET I would stick to the old version.

However, as you have already experienced, supporting netstandard 1.0 &le; x &lt; 2.0 requires conditional compilation, which I'd like to avoid. As you said, the client is responsible of the version he's using, and if he wants to use _resourcelib_, he has to use either .NET Framework or .NET Standard &ge; 2.0.

**Comment by jairbubbles** [comment]
I was more talking about the .NET Framework version. You should keep .NET Framework 2.0 for maximum compatibility.

And have a .NET Standard 2.0 version for more modern platforms / targets.

**Comment by thoemmi** [comment]
Though I'm not convinced that we still should support .NET 2.0 (Microsoft stopped supporting .NET 2.0 SP2 [7/12/2011](https://support.microsoft.com/en-us/lifecycle/search?sort=PN&alpha=.NET%20Framework&Filter=FilterNO), that's more than 6(!) years ago), I've enabled both .NET 2.0 and .NET 3.5.

**Comment by jairbubbles** [comment]
As it has no impact on our side I think it's a wise choice.

Regarding 4.5.2 I think it would be better to target 4.0. Since that version .NET Framework is upgraded in-place. So even on applications that target 4.0 it always uses the latest version installed on the machine. 

If we compare to Json.Net:
image

Or NUnit:
image

They both target `2.0`, `3.5`, `4.0`, `4.5`. I'm not sure I see the point of targetting `4.0` and `4.5`. Not sure I understand why they target both two versions of .NET Standard.

**Comment by thoemmi** [comment]
I've changed the target frameworks to `net20`, `net35`, `net40`, `net45`, and `netcoreapp2.0` (the last one will be replaced by `netstandard2.0` once System.Drawing.Common is fixed). The additional `net45` increases the package size by 65 kB to 328 kB, so I don't care.

**Comment by thoemmi** [comment]
> I might be mistaken but as you're referencing a prerelease package you won't be able to release a non prelease package for the lib.

That's right. But we can publish a prerelease of resourcelib and update it as soon as System.Drawing.Common is final.

**Pull request merged**
