### PR TITLE
Update To Vs2017

### PR DESCRIPTION
**Pull request by jairbubbles**
- Use `<PackageReference>` in .csproj
- Restore package before building
- No need to install NUnit anymore, it's bootstrapped in test project + added a test Target in this project
- Use `vswhere` to locate VS / MsBuild
- Udate MsBuild community build tasks (sadly I couldn't boostrap it for the global project)

### CODE REVIEW

**Comment by thoemmi** [comment]
Please add `packages/` to `.gitignore`, otherwise Visual Studio considers all referenced packages as pending changes.

**Comment by jairbubbles** [comment]
It's not needed with Visual Studio 2017 anymore when you use `<packagereference>`. Packages are directly consumed from the global NuGet packages cache (`%userprofile%/.nuget/packages` by default).

**Comment by thoemmi** [comment]
D'oh. I've checked out your PR with the old `packages` folder still in place :persevere: I even blogged about [cleaning your NuGet cache regularly](https://thomasfreudenberg.com/archive/2017/04/21/cleaning-nugets-cache/) some time ago.

**Comment by thoemmi** [comment]
Fixed with #59

**Pull request closed without merging**
