### PR TITLE
Fix typo user32,dll -> user32.dll

### PR DESCRIPTION
**Pull request by MaxXor**

### CODE REVIEW

**Comment by dblock** [comment]
Thanks! I guess we don't use this method ... how did you run into this?

**Comment by MaxXor** [comment]
Would you mind releasing a new version which includes this fix?

**Comment by dblock** [comment]
@icnocop @thoemmi been a while ... I don't have a windows box anymore :)

**Comment by hakito** [comment]
@dblock DestroyIcon and CreateIconIndirect are unused external methods. Why don't we remove them? They are internal anyway.

**Comment by dblock** [comment]
I agree, go for it.

**Pull request merged**
